//menupanel
document.write('<div data-role="panel" data-position-fixed="true" data-display="overlay" data-theme="a" data-overlay-theme="a" id="nav-panel"> <ul class="lnb_top"> <li><a href="#"><span></span><em>로그인</em></a></li> <li><a href="#"><span></span><em>고객센터</em></a></li> <li><a href="#" data-rel="close"></a></li> </ul> <ul class="lnb_tab lnb_tab1"> <li><a href="#"><span></span><em>해외</em></a></li> <li><a href="#"><span></span><em>국내</em></a></li> <li><a href="#"><span></span><em>항공권</em></a></li> </ul> <ul class="lnb_tab_c lnb_tab_c1"> <li><a href="#">유럽/아프리카/인도</a></li> <li><a href="#">동남아</a></li> <li><a href="#">중국</a></li> <li><a href="#">홍콩/대만</a></li> <li><a href="#">일본</a></li> <li><a href="#">괌/사이판/팔라우</a></li> <li><a href="#">호주/뉴질랜드/피지</a></li> <li><a href="#">미주/하와이/중남미</a></li> </ul> <ul class="lnb_tab_c lnb_tab_c2"> <li><a href="#">제주도</a></li> <li><a href="#">내륙/섬</a></li> <li><a href="#">국내항공</a></li> <li><a href="#">국내숙박</a></li> <li><a href="#">아! 대한민국</a></li> </ul> <ul class="lnb_tab lnb_tab2"> <li><a href="#"><span></span><em>호텔</em></a></li> <li><a href="#"><span></span><em>허니문</em></a></li> <li><a href="#"><span></span><em>콜프</em></a></li> </ul> <ul class="lnb_tab_c lnb_tab_c5"> <li><a href="#">동남아</a></li> <li><a href="#">남태평양</a></li> <li><a href="#">유럽</a></li> <li><a href="#">미주(하와이)</a></li> <li><a href="#">칸쿤/로스카보스</a></li> <li><a href="#">몰디브</a></li> <li><a href="#">부산출발</a></li> </ul> <ul class="lnb_tab_c lnb_tab_c6"> <li><a href="#">동남아</a></li> <li><a href="#">중국</a></li> <li><a href="#">일본</a></li> <li><a href="#">괌/사이판</a></li> <li><a href="#">미주(하와이)</a></li> <li><a href="#">특가/연휴</a></li> </ul> <ul class="lnb_tab lnb_tab3"> <li><a href="#"><span></span><em>테마</em></a></li> <li><a href="#"><span></span><em>이벤트</em></a></li> <li><a href="#"><span></span><em>기획전</em></a></li> </ul> <ul class="lnb_tab lnb_tab4"> <li><a href="#"><span></span><em>회사소개</em></a></li> </ul> <ul class="lf_sns"> <li><a href="http://blog.naver.com/lottejtbblog"><span></span><span>Lotte Holidays 블로그</span></a></li> <li><a href="https://story.kakao.com/ch/lottejtb/"><span></span><span>Lotte Holidays 카카오스토리</span></a></li> <li><a href="https://www.facebook.com/lottejtbofficial/"><span></span><span>Lotte Holidays 페이스북</span></a></li> <li><a href="https://www.instagram.com/lotteholidays/"><span></span><span>Lotte Holidays 인스타램</span></a></li> </ul> <ul class="lf_golink"> <li><a href="#">여행약관</a></li> <li><a href="#">이용약관</a></li> <li><a href="#">해외여행자 보험약관</a></li> <li><a href="#">개인정보 처리방침</a></li> <li><a href="#">찾아오시는 길</a></li> <li><a href="#">매장안내</a></li> </ul> </div>');
//user panel
document.write('<div data-role="panel" data-position="right" data-position-fixed="true" data-display="overlay" data-theme="a" id="add-form">');
document.write('<form class="userform">');
document.write('<h2>Login</h2>');
document.write('<label for="name">Username:</label>');
document.write('<input type="text" name="name" id="name" value="" data-clear-btn="true" data-mini="true">');
document.write('<label for="password">Password:</label><input type="password" name="password" id="password" value="" data-clear-btn="true" autocomplete="off" data-mini="true">');
document.write('<div class="ui-grid-a">');
document.write('<div class="ui-block-a">');
document.write('<a href="#" data-rel="close" class="ui-btn ui-shadow ui-corner-all ui-btn-b ui-mini">Cancel</a>');
document.write('</div>');
document.write('<div class="ui-block-b">');
document.write('<a href="#" data-rel="close" class="ui-btn ui-shadow ui-corner-all ui-btn-a ui-mini">Save</a>');
document.write('</div></div></form></div>');   

//POPUP
	//카테고리팝업
document.write('	<div data-role="popup" id="navPop" class="ui-content" data-overlay-theme="b" data-position-to="window">');
document.write('	<fieldset data-role="controlgroup">');
document.write('		<legend>카테고리선택</legend>');
document.write('		<div class="cateWrap">');
document.write('			<input type="radio" name="radio-choice-1" id="radio-choice-11" value="choice-11" checked="checked">');
document.write('			<label for="radio-choice-11">1DEPTH</label>');
document.write('			<input type="radio" name="radio-choice-1" id="radio-choice-12" value="choice-12">');
document.write('			<label for="radio-choice-12">1DEPTH</label>');
document.write('			<input type="radio" name="radio-choice-1" id="radio-choice-13" value="choice-13">');
document.write('			<label for="radio-choice-13">1DEPTH</label>');
document.write('			<input type="radio" name="radio-choice-1" id="radio-choice-14" value="choice-14">');
document.write('			<label for="radio-choice-14">1DEPTH</label>');
document.write('			<input type="radio" name="radio-choice-1" id="radio-choice-15" value="choice-15">');
document.write('			<label for="radio-choice-15">1DEPTH</label>');
document.write('		</div>');
document.write('	</fieldset>');
document.write('		<div data-role="footer" ><a href="#" data-rel="back" class="ui-btn align-c">Close</a></div>');
document.write('	 </div>');
	//카테고리팝업2
document.write('	 <div data-role="popup" id="navPop2" class="ui-content" data-overlay-theme="b" data-position-to="window">');
document.write('	<fieldset data-role="controlgroup">');
document.write('		<legend>카테고리선택2</legend>');
document.write('		<div class="cateWrap">');
document.write('			<input type="radio" name="radio-choice-2" id="radio-choice-21" value="choice-21" checked="checked">');
document.write('			<label for="radio-choice-21">2DEPTH</label>');
document.write('			<input type="radio" name="radio-choice-2" id="radio-choice-22" value="choice-22">');
document.write('			<label for="radio-choice-22">2DEPTH</label>');
document.write('			<input type="radio" name="radio-choice-2" id="radio-choice-23" value="choice-23">');
document.write('			<label for="radio-choice-23">2DEPTH</label>');
document.write('			<input type="radio" name="radio-choice-2" id="radio-choice-24" value="choice-24">');
document.write('			<label for="radio-choice-24">2DEPTH</label>');
document.write('			<input type="radio" name="radio-choice-2" id="radio-choice-25" value="choice-25">');
document.write('			<label for="radio-choice-25">2DEPTH</label>');
document.write('		</div>');
document.write('	</fieldset>');
document.write('		<div data-role="footer" ><a href="#" data-rel="back" class="ui-btn align-c">Close</a></div>');
document.write('	 </div>');
	//상품평팝업
document.write('	 <div data-role="popup" id="commentPop" class="ui-content" data-overlay-theme="b" data-position-to="window">');
document.write('	<fieldset data-role="controlgroup">');
document.write('		<legend>고객상품평</legend>');
document.write('			<ul data-role="listView">');
document.write('				<li>');
document.write('					<input type="text" name="user" id="un2" value="" placeholder="제목을 입력하세요" data-theme="a">');
document.write('				</li>');
document.write('				<li>');
document.write('					<span class="rating"><em>☆</em><em>☆</em><em>☆</em><em>☆</em><em>☆</em></span>');
document.write('				</li>');
document.write('				<li>');
document.write('					<input type="text" name="user" id="un2" value="" placeholder="제목을 입력하세요" data-theme="a">');
document.write('				</li>');
document.write('			</ul>');
document.write('	</fieldset>');
document.write('		<div data-role="footer" ><a href="#" data-rel="back" class="ui-btn align-c">닫기</a><a href="#" data-rel="submit" class="ui-btn align-c">상품평 저장</a></div>');
document.write('	 </div>');
	//표준약관팝업
document.write('	 <div data-role="popup" id="policyPop" class="ui-content" data-overlay-theme="b" data-position-to="window">');
document.write('	<fieldset data-role="controlgroup">');
document.write('		<legend>표준약관</legend>');
document.write('		<div class="cateWrap">');
document.write('			<div class="box_right">');
document.write('	<h5 class="info_title">소비자피해보상규정 (공정거래위원회 고시 제2014-4호)</h5>');
document.write('	<ul class="info_list01">');
document.write('		<li>1) 여행취소로 인한 피해');
document.write('			<ul class="info_list02">');
document.write('				<li>1. 여행사의 귀책사유로 여행사가 취소하는 경우');
document.write('					<ul class="info_list03">');
document.write('						<li>- 여행개시 30일전(~30)까지 통보 시 : 계약금 환급</li>');
document.write('						<li>- 여행개시 20일 전까지 통보 시: 여행요금의 10% 배상</li>');
document.write('						<li>- 여행개시 10일 전까지 통보 시: 여행요금의 15% 배상</li>');
document.write('						<li>- 여행개시 8일 전까지 통보 시 : 여행요금의 20% 배상</li>');
document.write('						<li>- 여행개시 1일 전까지 통보 시: 여행요금의 30% 배상</li>');
document.write('						<li>- 여행 당일 통보 시 - 여행요금의 50% 배상</li>');
document.write('					</ul>');
document.write('				</li>');
document.write('				<li class="mt20">2.  여행자의 여행계약 해지 요청이 있는 경우');
document.write('					<ul class="info_list03">');
document.write('						<li>- 여행개시 30일전(~30)까지 통보 시 : 계약금 환급</li>');
document.write('						<li>- 여행개시 20일 전까지 통보 시 : 여행요금의 10% 배상</li>');
document.write('						<li>- 여행개시 10일 전까지 통보 시 : 여행요금의 15% 배상</li>');
document.write('						<li>- 여행개시 8일 전까지 통보 시 : 여행요금의 20% 배상</li>');
document.write('						<li>- 여행개시 1일 전까지 통보 시 : 여행요금의 30% 배상</li>');
document.write('						<li>- 여행 당일 통보 시 - 여행요금의 50% 배상</li>');
document.write('						<li>- 여행참가자 수의 미달로 여행개시 7일 전까지 여행계약 해제 통지 시 : 계약금 환급</li>');
document.write('						<li>- 여행참가자 수의 미달로 인한 여행개시 7일 전까지 통지기일 미 준수* 여행개시 1일전까지 통지 시</li>');
document.write('						<li>- 여행요금의 30% 배상* 여행출발 당일 통지 시</li>');
document.write('						<li>- 여행요금의 50% 배상</li>');
document.write('						<li>※ 공정거래위원회 고시 제2014-4호 소비자분쟁해결기준에 의한 것으로 2014년 3월 21일 여행상품 예약자부터 적용</li>');
document.write('					</ul>');
document.write('				</li>');
document.write('			</ul>');
document.write('		</li>');
document.write('		<li class="mt20">2) 여행사의 계약조건 위반으로 인한 피해(여행 후)');
document.write('			<ul class="info_list02">');
document.write('				<li>- 신체손상이 없을 때 최대 여행 대금 범위 내에서 배상</li>');
document.write('				<li>- 신체손상 시 위자료, 치료비, 휴업손해 등 배상</li>');
document.write('			</ul>');
document.write('		</li>');
document.write('		<li class="mt20">3) 여행계약의 이행에 있어 여행종사자의 고의 또는 과실로 여행자에게 손해를 끼쳤을 경우');
document.write('			<ul class="info_list02">');
document.write('				<li>- 여행자가 입은 손해 배상</li>');
document.write('				<li class="mt10">※ 주의사항</li>');
document.write('				<li class="mt5"> 전세기 및 일부 상품은 공정위에서 지정한 여행업 표준약관 제 5조(특약), 제 20조(기타사항)에 의거하여 별도의 보상규정이 적용되오니<br> 상품 구매 시 유의하시기 바랍니다.</li>');
document.write('			</ul>');
document.write('		</li>');
document.write('	</ul>');
document.write('</div>');
document.write('		</div>');
document.write('	</fieldset>');
document.write('		<div data-role="footer" ><a href="#" data-rel="back" class="ui-btn align-c">닫기</a></div>');
document.write('	 </div>');
	//리스트정렬팝업
document.write('	 <div data-role="popup" id="selPop" class="ui-content" data-overlay-theme="b" data-position-to="window">');
document.write('	 		<fieldset data-role="controlgroup">');
document.write('	 		<legend>정렬선택</legend>');
document.write('	 		<input type="radio" name="radio-choice-3" id="radio-choice-31" value="choice-31" checked="checked">');
document.write('	 		<label for="radio-choice-31">추천상품순</label>');
document.write('	 		<input type="radio" name="radio-choice-3" id="radio-choice-32" value="choice-32">');
document.write('	 		<label for="radio-choice-32">가격낮은순</label>');
document.write('	 		<input type="radio" name="radio-choice-3" id="radio-choice-33" value="choice-33">');
document.write('	 		<label for="radio-choice-33">가격높은순</label>');		
document.write('	 		</fieldset>');
document.write('	 		<div data-role="footer" ><a href="#" data-rel="back" class="ui-btn align-c">Close</a></div>');
document.write('	 	 </div>');
		//팝업
document.write('	<div data-role="popup" id="popupLogin" data-overlay-theme="b" data-position-to="window">');
document.write('		<form>');
document.write('			<div style="padding:10px 20px;">');
document.write('				<h3>Please sign in</h3>');
document.write('				<label for="un" class="ui-hidden-accessible">Username:</label>');
document.write('				<input type="text" name="user" id="un" value="" placeholder="username" data-theme="a">');
document.write('				<label for="pw" class="ui-hidden-accessible">Password:</label>');
document.write('				<input type="password" name="pass" id="pw" value="" placeholder="password" data-theme="a">');
document.write('				<button type="submit" class="ui-btn ui-corner-all ui-shadow ui-btn-b ui-btn-icon-left ui-icon-check">Sign in</button>');
document.write('			</div>');
document.write('		</form>');
document.write('	</div>');
	// 다른이용항공팝업2
document.write('	 <div data-role="popup" id="airPop" class="ui-content" data-overlay-theme="b" data-position-to="window">');
document.write('	<fieldset data-role="controlgroup">');
document.write('		<legend>다른항공이용</legend>');
document.write('		<div class="cateWrap">');
document.write('			<input type="radio" name="radio-choice-4" id="radio-choice-41" value="choice-41" checked="checked">');
document.write('			<label for="radio-choice-41">아시아나</label>');
document.write('			<input type="radio" name="radio-choice-4" id="radio-choice-42" value="choice-42">');
document.write('			<label for="radio-choice-42">대한항공</label>');
document.write('			<input type="radio" name="radio-choice-4" id="radio-choice-43" value="choice-43">');
document.write('			<label for="radio-choice-43">제주항공</label>');
document.write('			<input type="radio" name="radio-choice-4" id="radio-choice-44" value="choice-44">');
document.write('			<label for="radio-choice-44">아시아나</label>');
document.write('			<input type="radio" name="radio-choice-4" id="radio-choice-45" value="choice-45">');
document.write('			<label for="radio-choice-45">대한항공</label>');
document.write('		</div>');
document.write('	</fieldset>');
document.write('		<div data-role="footer" ><a href="#" data-rel="back" class="ui-btn align-c">Close</a></div>');
document.write('	 </div>');
	//광고성정보 수신동의
document.write('	<div data-role="popup" id="alramPop_adver" class="ui-content" data-overlay-theme="b" data-position-to="window">');
document.write('		<div data-role="header" >광고성정보 수신동의</div>');
document.write('			<div data-role="content" >');
document.write('		            <p>롯데제이티비에서 해당 기기로 영리목적 광고성 정보를 전송하려고 합니다.<br/>');
document.write('		            앱스토어에서 다운받으시겠습니까?</p>');
document.write('		            <span>해당 설정은 롯데제이티비 APP > 좌측메뉴 하단 > 설정에서 변경 가능합니다.</span>');
document.write('		        </div>');
document.write('			<div data-role="footer" ><a href="#" data-rel="back" class="ui-btn align-c">동의안함</a><a href="#" data-rel="back" class="ui-btn align-c point">동의</a></div>');
document.write('		 </div>');
	//앱업데이트알림
document.write('		<div data-role="popup" id="appalramPop" data-overlay-theme="b" data-position-to="window">');
document.write('		    <div data-role="header" >앱업데이트알림</div>');
document.write('				<div data-role="content" >');
document.write('			            <p>새로운 버젼이 업데이트 되었습니다.<br/>');
document.write('			            앱스토어에서 다운받으시겠습니까?</p>');
document.write('			            <span>확인 클릭시 앱스토어로 이동합니다.</span>');
document.write('			        </div>');
document.write('				<div data-role="footer" ><a href="#" data-rel="back" class="ui-btn align-c">취소</a><a href="#" data-rel="back" class="ui-btn align-c">확인</a></div>');
document.write('			</div>');
	//롯데 JTB알림 Y
document.write('			<div data-role="popup" id="alramPop_jtbN" data-overlay-theme="b" data-position-to="window">');
document.write('			   <div data-role="header" >광고성정보 수신동의</div>');
document.write('				<div data-role="content" >	        ');
document.write('			            <p>고객님의 광고성정보 수신동의가 "수신안함"처리<br/>');
document.write('		            되었습니다. (롯데제이티비,YYYY.MM.DD.HH)</p>');
document.write('		        </div>');
document.write('			<div data-role="footer" ><a href="#" data-rel="back" class="ui-btn align-c">확인</a></div>');
document.write('		</div>');
	//롯데 JTB알림 N
document.write('			<div data-role="popup" id="alramPop_jtbY" data-overlay-theme="b" data-position-to="window">');
document.write('			   <div data-role="header" >광고성정보 수신동의</div>');
document.write('				<div data-role="content" >	        ');
document.write('			            <p>고객님의 광고성정보 수신동의가 "수신함"처리<br/>');
document.write('		            되었습니다. (롯데제이티비,YYYY.MM.DD.HH)</p>');
document.write('		        </div>');
document.write('			<div data-role="footer" ><a href="#" data-rel="back" class="ui-btn align-c">확인</a></div>');
document.write('		</div>');
	//찜알림
document.write('	<div data-role="popup" id="favoPop" class="ui-content" data-overlay-theme="b" data-position-to="window">');
document.write('			   <div data-role="header" >찜하기</div>');
document.write('			<div data-role="content" >');
document.write('		            <p>선택한 여행상품을 찜하기에 담았습니다.</p>');
document.write('		            <span>찜!여행상품 목록에서 확인하시겠습니까?</span>');
document.write('		        </div>');
document.write('			<div data-role="footer" ><a href="#" data-rel="back" class="ui-btn align-c">계속여행</a><a href="#" data-rel="back" class="ui-btn align-c point">목록확인</a></div>');
document.write('		 </div>');